image: Visual Studio 2019
build_script:
  - set JAVA_HOME="C:\Program Files\Java\jdk16"
test_script:
  - ./gradlew.bat clean test --info
notifications:
  - provider: Email
    to:
      - miniwolf1508@gmail.com
      - costa@hotmail.dk
    on_build_failure: true