image: Visual Studio 2017
build_script:
  - set JAVA_HOME="C:\Program Files\Java\jdk11"
test_script:
  - ./gradlew.bat test --info
notifications:
  - provider: Email
    to:
      - miniwolf1508@gmail.com
      - costa@hotmail.dk
    on_build_failure: true