language: java
jdk:
  - oraclejdk8

script:
  - ant build.modules

notifications:
  email:
    recipients:
      - miniwolf1508@gmail.com
      - costa@hotmail.dk
    on_success: never # default: change
    on_failure: always # default: always