language: java
install: ant build.modules
jdk:
  - oraclejdk8

notifications:
  email:
    recipients:
      - miniwolf1508@gmail.com
      - costa@hotmail.dk
    on_success: never # default: change
    on_failure: always # default: always