language: java
matrix:
  include:
    - os: linux
      before_install:
        - sudo apt-get install at-spi2-core
        - export DISPLAY=:99.0
        - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16
      script:
        - set -e
        - ./build_linux.sh javac
        - ./run_linux.sh java
    - os: osx
      script:
        - set -e
        - ./build_osx.sh javac
        - ./run_osx.sh java
  allow_failures:
    - os: osx

jdk: openjdk11
notifications:
  email:
    recipients:
      - miniwolf1508@gmail.com
      - costa@hotmail.dk
    on_success: never # default: change
    on_failure: always # default: always