language: java
before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
install: ant build.modules
jdk:
  - openjdk10

notifications:
  email:
    recipients:
      - miniwolf1508@gmail.com
      - costa@hotmail.dk
    on_success: never # default: change
    on_failure: always # default: always