language: java
before_install:
  - "sudo apt-get install at-spi2-core"
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
jdk:
  - openjdk11
script:
  - ./build.sh javac
  - ./run.sh java

notifications:
  email:
    recipients:
      - miniwolf1508@gmail.com
      - costa@hotmail.dk
    on_success: never # default: change
    on_failure: always # default: always