package com.fagi.http.server.validation;

// TODO: zargess - javadoc

/**
 * @author Marcus Haagh
 */
public enum RestEndpointValidationError {
    PATH_MISSING_ON_API_CLASS,
    PATHS_DUPLICATED_IN_API_CLASSES,
    PATH_MISSING_ON_METHOD,
    PATH_PARAM_NOT_IN_TEMPLATE,
    PATH_PARAM_NOT_DEFINED,
    PATH_PARAM_DUPLICATE_IN_TEMPLATE,
    PATH_PARAM_DUPLICATE_ANNOTATION,
    HTTP_METHOD_ANNOTATION_MISSING,
    CONSUMES_ANNOTATION_MISSING,
    CONSUMES_TEXT_ONLY_ALLOWS_STRING_OR_PRIMITIVE_TYPE,
    PRODUCES_ANNOTATION_MISSING,
    PRODUCES_TEXT_ONLY_ALLOWS_STRING_OR_PRIMITIVE_RETURN_TYPE,
    BODY_PARAM_IN_HTTP_GET_ENDPOINT,
    BODY_PARAM_MISSING,
    ONLY_ONE_BODY_PARAM_ALLOWED,
    QUERY_PARAM_TYPE_NOT_ALLOWED,
    HEADER_PARAM_TYPE_NOT_ALLOWED,
    VOID_RETURN_TYPE_NOT_ALLOWED,
    VOID_RETURN_TYPE_WHEN_PRODUCES_DEFINED
}
